### ISSUE TITLE
テスト実行のDesign Document

### ISSUE THREAD

**Issue by shibukawa** [future-architect/go-twowaysql#31]
# SQLテストランナー

## コンテキストとスコープ

アプリケーションコードを書かずに、SQLだけで高速にテスト駆動開発を行い、品質の高いSQLを書く環境を用意する。

Markdownに書かれたテストケースを読み込んで、テストを実行する。

また、サブの機能としてtwowaysql.RunTestメソッドを提供し、ユニットテストに組み込めるようにする。

## ゴール

* プロジェクトで使用するSQL類を一括でテストする
* テストケースはSQLを書いたMarkdownで記述する
  * テストケースには、テストデータ、パラメータ、結果を含む

## ゴール外

* カバレッジ計測は将来的にはやりたいがコアへの変更が必要なのでこのDesign Docの対象外とする
* 実行時にシーケンシャルスキャンがあったらエラーにするなど

## 実際のデザイン

Markdownに書かれたテストケースの抽出を行い、実行をする。

Markdownはセクションタイトルのルールを定めて、テストケースの情報を記述する。

実行時はまずはトランザクションでくくって、テスト終了後にDBを戻せるようにする。事前に投入するデータがあればそれを入れる。その後対象のクエリーを実行し、テストケースに書かれた検証手法（レスポンス、あるいはDBの内容、外部のファイルなどのチェック）で検証する。最後にロールバックする

テストデータは以下の形式をサポート

* YAML
* SQL

パラメータと期待する結果はYAML形式をサポート

また、アプリケーションのテストコードに追加可能な関数も提供する。

```go
sqltest.RunTest(t, db, "testdata/sqlr")
```

## システムコンテキスト図

```mermaid
graph TD;

Markdown -->|読み込み| テストランナー
テストランナー --> テスト結果
```

## コードと疑似コード

以下はMarkdownのサンプル。

````md
# タイトル

```sql
SELECT email, name FROM users WHERE name=/*name*/'bob';
```

## Test

テストの事前データはYAMLでコンパクトに書いて各テーブルにinsertする想定。名前に(reset)がついていたら、一度テーブルの中をすべて空にしてからinsert。Testセクション以下は全テストの前で毎回実行されるもの（結果は毎回rollback)

```yaml
fixtures:
  - users
    - [employee_no, dept_no, first_name, last_name, email]
	- [1, 10, Evan, MacMans, evanmacmans@example.com]
    - [2, 11, Malvin, FitzSimons, malvinafitzsimons@example.com]
    - [3, 12, Jimmie, Bruce, jimmiebruce@example.com]
```

あるいはSQLを書いても良い。これもtx.Execで実行される。

```sql
INSERT INTO persons(employee_no, dept_no, first_name, last_name, email, created_at) VALUES
			(1, 10, 'Evan', 'MacMans', 'evanmacmans@example.com', CURRENT_TIMESTAMP),
			(2, 11, 'Malvina', 'FitzSimons', 'malvinafitzsimons@example.com', CURRENT_TIMESTAMP),
			(3, 12, 'Jimmie', 'Bruce', 'jimmiebruce@example.com', CURRENT_TIMESTAMP)
			;
```

### Case: query test with alice

各テストケースではYAMLを書く

fixture/fixturesは全体のfixturesに追加して入れられる。
param/paramsは実行パラメータ
結果は以下のキーで記述する

- result: tx.Selectで実行。結果は順番通りの比較

```yaml
fixtures:
  - users
	- ["", "", ""]
params: { name: "Alice" }
result:
  - { email: alice@example.com, name: Alice }
```

### Case: exec test

deleteやupdate、insertの場合はその後の検証用クエリーをtestQueryに書く。

```yaml
fixtures:
  - users
	- ["", "", ""]
params: { name: "Alice" }
testQuery: "select count(id) as count  from users"
result:
  - { count: 1 }
```
````

## 制約の度合い

* GitHubなどのMarkdownで記述でき、複雑な記法とならない程度のMarkdownの書き方にする必要がある
